# Generated by Django 5.0.6 on 2024-06-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_dead_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='currencies')),
                ('abbreviation', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ScienceDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='old_dead_app1.sciencedegree')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='old_dead_app1.teachingdegree')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=100)),
                ('external_teacher', models.BooleanField(default=False)),
                ('salary', models.IntegerField()),
                ('capacity', models.IntegerField(verbose_name='Capacity in hours per week')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old_dead_app1.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='old_dead_app1.currency')),
                ('science_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old_dead_app1.sciencedegree')),
                ('teaching_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old_dead_app1.teachingdegree')),
            ],
        ),
    ]
