# Generated by Django 5.0.6 on 2024-05-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old_dead_app1', '0002_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
