# Generated by Django 5.0.6 on 2024-05-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old_dead_app1', '0003_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
    ]
