# Generated by Django 5.0.6 on 2024-05-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old_dead_app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
