# Generated by Django 5.0.6 on 2024-05-24 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_dead_app1', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(default='qqq', on_delete=django.db.models.deletion.CASCADE, to='old_dead_app1.department'),
            preserve_default=False,
        ),
    ]
