# Generated by Django 5.0.6 on 2024-05-24 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_dead_app1', '0003_department_worker_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания департамента'),
            preserve_default=False,
        ),
    ]
